<a href="https://colab.research.google.com/github/anandtopu/100DaysOfMachineLearning/blob/master/Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 2: Tensors and Data

# Tensors

In [ ]:
import torch

In [ ]:
x = torch.randn((2,3,4))
x

tensor([[[-0.6821,  2.0452, -0.8155,  1.0177],
         [ 0.0580, -0.2678,  0.3856,  0.6357],
         [-2.1011,  0.4320, -1.1815, -1.2482]],

        [[ 1.0114, -0.1282,  1.1403,  0.2782],
         [ 0.8214,  1.9457,  0.9430, -0.0976],
         [ 2.0308,  0.7842,  0.0646, -1.3259]]])

In [ ]:
y = torch.randn_like(x)
z = x + y
print(x, '\n', y, '\n', z)

tensor([[[-0.6821,  2.0452, -0.8155,  1.0177],
         [ 0.0580, -0.2678,  0.3856,  0.6357],
         [-2.1011,  0.4320, -1.1815, -1.2482]],

        [[ 1.0114, -0.1282,  1.1403,  0.2782],
         [ 0.8214,  1.9457,  0.9430, -0.0976],
         [ 2.0308,  0.7842,  0.0646, -1.3259]]]) 
 tensor([[[ 0.5634,  0.1945,  0.3218,  2.0072],
         [-0.0617,  2.1441,  0.6317, -0.4293],
         [-0.3106,  1.6302, -0.8277,  0.6412]],

        [[ 0.6555, -1.2323, -0.1177, -0.7839],
         [-2.0265, -2.8610, -0.4756,  0.9021],
         [-0.2604,  0.6805, -0.6270,  0.2951]]]) 
 tensor([[[-0.1187,  2.2397, -0.4937,  3.0250],
         [-0.0037,  1.8763,  1.0173,  0.2064],
         [-2.4117,  2.0622, -2.0092, -0.6069]],

        [[ 1.6669, -1.3605,  1.0225, -0.5057],
         [-1.2051, -0.9153,  0.4674,  0.8046],
         [ 1.7704,  1.4647, -0.5624, -1.0309]]])


In [ ]:
x.device

device(type='cpu')

In [ ]:
x.shape

torch.Size([2, 3, 4])

In [ ]:
x.dtype

torch.float32

In [ ]:
w = torch.zeros((3,4,2))
w

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
x.mean()

tensor(0.2394)